name: Generate PDF Resumes

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Download Eisvogel Template
        run: |
          mkdir -p ~/.pandoc/templates
          wget -O ~/.pandoc/templates/eisvogel.latex https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/refs/heads/master/template-multi-file/eisvogel.latex
          wget -O ~/.pandoc/templates/passoptions.latex https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/refs/heads/master/template-multi-file/passoptions.latex
          wget -O ~/.pandoc/templates/fonts.latex https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/refs/heads/master/template-multi-file/fonts.latex
          wget -O ~/.pandoc/templates/font-settings.latex https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/refs/heads/master/template-multi-file/font-settings.latex
          wget -O ~/.pandoc/templates/common.latex https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/refs/heads/master/template-multi-file/common.latex

      - name: Convert Markdown to PDF (Русский)
        run: |
          pandoc ru/index.md -f markdown -t pdf --pdf-engine=xelatex --template=eisvogel.latex -V lang=ru -o resume_ru.pdf

      - name: Convert Markdown to PDF (English)
        run: |
          pandoc en/index.md -f markdown -t pdf --pdf-engine=xelatex --template=eisvogel.latex -V lang=en -o resume_en.pdf

      - name: Commit and Push PDFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add resume_ru.pdf resume_en.pdf
          git commit -m "Автоматическое обновление resume PDFs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}